from sparkling_wine_classes import Champagne, Cremant, Prosecco, Mousseux
sparkling_wine = [
    Champagne("Nicolas Feuillatte Grande Réserve", 24.90, 5.0, True),
    Champagne("Cordon Rouge GH.Mumm", 29.90, 5.0, True),
    Champagne("De Castellane", 20.10, 4.25, True),
    Champagne("Charles Vincent", 18.15, 5.0, True),
    Champagne("Canard-Duchene", 25.50, 5.0, True),
    Champagne("Charles de Courance", 18.49, 4.13, True),
    Champagne("Tsarine", 27.55, 5.0, True),
    Champagne("Jeanmaire à Épernay", 18.05, 4.2, True),
    Champagne("Vranken Demoiselle E.O.", 31.05, 5.0, True),
    Champagne("Veuve Clicquot", 44.40, None, True),
    Champagne("Moët & Chandon Brut Impérial", 39.65, None, True),
    Champagne("Pommery Brut Royal", 34.75, 4.67, True),
    Champagne("Laurent Perrier La Cuvée", 36.55, 5.0, True),
    Champagne("Demoiselle Rosé Vranken", 29.35, 5.0, True),
    Champagne("Rosé Tsarine", 31.99, 4.5, True),
    Champagne("Alfred Rothschild & Co Brut Excellence", 27.60, 4.8, True),
    Champagne("Veuve Clicquot Rosé", 51.90, None, True),
    Champagne("Charles de Courance Cuvée Spéciale", 26.55, 4.33, True),
    Champagne("Baron Fuente Tradition", 18.00, None, True),
    Champagne("Baron Fuente Blanc de Blancs", 25.05, None, True),
    Champagne("Cristal Louis Roederer", 217.90, None, True),
    Champagne("Moët & Chandon Grand Vintage", 50.90, None, True),
    Champagne("Dom Perignon Vintage Lenny Kravitz 2008", 1251.00, None, True),
    Champagne("Jéroboam Armand de Brignac Brut Gold", 2665.00, None, True),
    Champagne("Henriot Blanc de Blancs", 94.00, None, True),
    Champagne("Piper-Heidsieck Rosé Sauvage", 36.50, None, True),
    Champagne("Laurent-Perrier Blanc de Blancs Nature", 149.00, None, True),
    Champagne("Pol Roger Réserve Brut Magnum", 281.00, None, True),
    Champagne("Nicolas Feuillatte Rosé Grande Réserve Magnum", 82.54, None, True),
    Champagne("Charles Orban Blanc de Noirs", 36.53, None, True),
    Champagne("Taittinger Prestige Rosé Étui", 66.78, None, True),
    Champagne("Veuve Clicquot Ice Yellow Jacket Brut", 103.00, None, True),
    Champagne("Bruno Paillard Blanc de Blancs Grand Cru", 158.00, None, True),
    Champagne("Cattier Brut Blanc de Blancs Premier Cru", 117.00, None, True),
    Champagne("Charles de Cazanove Stradivarius Gold 2009", 75.32, None, True),
    Champagne("Gosset Grande Réserve Brut", 55.73, None, True),
    Champagne("Taittinger Prélude Étui", 65.99, None, True),
    Champagne("Veuve Leroy AOP Brut", 116.96, 5.0, True),
    Champagne("Champagne Baron Fuente Galipettes", 26.80, None, True),
    Champagne("Canard Duchene Cuvée P181 Extra Brut", 29.35, None, True),
    Champagne("Moët & Chandon Demi-Sec Ice Impérial", 49.95, None, True),
    Champagne("Piper-Heidsieck Vintage 2012", 134.00, None, True),
    Champagne("Pol Roger Extra Brut", 146.00, None, True),
    Champagne("Magnum Perrier-Jouët Grand Brut", 236.00, None, True),
    Champagne("Magnum Ruinart Blanc de Blancs", 360.00, None, True),
    Champagne("Leclerc-Briant La Croisette 2015", 2988.00, None, True),
    Champagne("Charles Heidsieck Rosé", 109.00, None, True),
    Champagne("Gosset Grand Rosé", 129.00, None, True),
    Champagne("Dom Pérignon Lenny Kravitz 2008", 1251.00, None, True),
    Champagne("Laurent-Perrier La Cuvée with 2 Flutes", 94.00, None, True),
    Champagne("Champagne Victoire Série Limitée Gold", 77.74, None, True),
    Champagne("Champagne Drappier Brut Pinot Noir", 45.08, None, True),
    Champagne("Charles de Courance Cuvée Spéciale", 26.55, 4.33, True),
    Champagne("Georges Clément Brut Tradition", 31.71, None, True),
    Champagne("Henriot Blanc de Blancs", 94.00, None, True),
    Champagne("Magnum Armand de Brignac Brut Gold", 2665.00, None, True),
    Champagne("Charles Orban Blanc de Noirs avec Étui", 36.53, None, True),
    Champagne("Jéroboam Armand de Brignac Brut Gold", 2665.00, None, True),
    Champagne("Champagne Taittinger Brut Réserve Magnum", 108.71, None, True),
    Champagne("Champagne Perrier-Jouët Blason Rosé", 160.00, None, True),
    Champagne("Champagne Nicolas Feuillatte Blanc de Blancs", 32.95, None, True),
    Champagne("Champagne Beaumont Des Crayères Blanc De Noirs Extra Brut", 25.95, None, True),
    Champagne("Champagne Gosset Grand Rosé", 129.00, None, True),
    Champagne("Champagne Deutz Brut Rosé", 59.66, None, True),
    Champagne("Champagne Charles Orban Brut Rosé", 31.45, None, True),
    Champagne("Champagne Lanson Le Black Label Brut", 34.95, None, True),
    Champagne("Champagne Laurent-Perrier Grand Siècle", 94.00, None, True),
    Champagne("Champagne Veuve Clicquot Brut Rosé", 51.90, None, True),
    Champagne("Champagne Drappier Brut Pinot Noir", 45.08, None, True),
    Champagne("Champagne Ruinart Blanc de Blancs", 360.00, None, True),
    Champagne("Champagne Piper-Heidsieck Brut Sauvage", 53.39, None, True),
    Champagne("Champagne Charles Heidsieck Blanc de Blancs", 75.02, None, True),
    Champagne("Champagne Charles Heidsieck Rosé", 109.00, None, True),
    Champagne("Champagne Taittinger Brut Prélude", 65.99, None, True),
    Champagne("Champagne Gosset Grande Réserve", 55.73, None, True),

    Cremant("Crémant d'Alsace Brut E. DURENMEYER", 5.95, 4.45, True, "Alsace"),
    Cremant("Crémant d'Alsace Brut WOLFBERGER", 7.65, 5.0, True, "Alsace"),
    Cremant("Crémant de Bourgogne Brut HONORE LOUIS", 6.79, 4.34, True, "Bourgogne"),
    Cremant("Crémant d'Alsace Rosé Pinot Noir E.DURENMEYER", 6.90, 4.25, True, "Alsace"),
    Cremant("Crémant d'Alsace Brut CONSTANCE MULLER REFLETS DE FRANCE", 8.55, 4.44, True, "Alsace"),
    Cremant("Crémant d'Alsace demi-Sec E.DURENMEYER", 6.25, 4.54, True, "Alsace"),
    Cremant("Crémant de Bourgogne Brut VEUVE AMBAL GRANDE CUVEE", 8.49, 5.0, True, "Bourgogne"),
    Cremant("Crémant de Bourgogne Brut Chardonnay HONORE LOUIS", 7.25, 4.23, True, "Bourgogne"),
    Cremant("Crémant d'Alsace Brut ARTHUR METZ", 6.55, 5.0, True, "Alsace"),
    Cremant("Crémant de Loire BELLECOURT LAGRAVIERE", 5.85, 4.33, True, "Loire"),
    Cremant("Crémant d'Alsace Brut Rosé WOLFBERGER", 8.69, 5.0, True, "Alsace"),
    Cremant("Crémant de Bordeaux Brut DEMOISELLE DE LANEZAC", 5.95, 4.32, True, "Bordeaux"),
    Cremant("Crémant de Bourgogne Brut DOMAINE GRACIEUX CHEVALIER REFLETS DE FRANCE", 8.69, 4.13, True, "Bourgogne"),
    Cremant("Crémant de Loire Brut LOUIS DE FORTIN REFLETS DE FRANCE", 7.19, 4.33, True, "Loire"),
    Cremant("Crémant de Loire Brut ACKERMAN", 6.90, None, True, "Loire"),
    Cremant("Crémant de Limoux AGUILA", 6.50, None, True, "Limoux"),
    Cremant("Crémant de Loire Brut CARREFOUR BIO", 7.75, 4.47, True, "Loire"),
    Cremant("Crémant de Bordeaux Rosé Merlot JAILLANCE", 6.95, None, True, "Bordeaux"),
    Cremant("Crémant de Bourgogne Brut Rosé VEUVE AMBAL GRANDE CUVEE", 8.49, 5, True, "Bourgogne"),
    Cremant("Crémant d'Alsace Brut d'Alsace CUVEE PRESTIGE ARTHUR METZ", 8.35, None, True, "Alsace"),
    Cremant("Crémant de Bourgogne Tastevinage VEUVE AMBAL", 7.99, 5, True, "Bourgogne"),
    Cremant("Crémant de Loire blanc brut MONCONTOUR", 7.50, None, True, "Loire"),
    Cremant("Crémant de Bourgogne brut CHARLES RANVILLE", 8.30, None, True, "Bourgogne"),
    Cremant("Crémant d'Alsace brut ARTHUR METZ", 9.80, None, True, "Alsace"),
    Cremant("Crémant du Jura brut FRUITIERES DE PUPILLIN", 8.89, None, True, "Jura"),
    Cremant("Crémant de Bourgogne MARIE AMBAL", 8.99, 5, True, "Bourgogne"),
    Cremant("Crémant de Die brut JAILLANCE", 6.99, None, True, "Die"),
    Cremant("Crémant de Bourgogne brut L'AURORE", 7.00, None, True, "Bourgogne"),
    Cremant("Crémant de Bourgogne brut C. DE L'AURORE", 6.50, None, True, "Bourgogne"),
    Cremant("Crémant de Bourgogne brut CHARLES RANVILLE", 7.10, None, True, "Bourgogne"),
    Cremant("Crémant d'Alsace Ice Rosé WOLFBERGER", 6.80, None, True, "Alsace"),
    Cremant("Crémant d'Alsace brut JEAN PERRIER & FILS", 10.90, None, True, "Alsace"),
    Cremant("Crémant de Bordeaux Brut MALESAN", 8.29, None, True, "Bordeaux"),
    Cremant("Crémant de Bourgogne brut ARTHUR METZ", 8.95, None, True, "Bourgogne"),
    Cremant("Crémant de Bourgogne brut CAVE DE BEBLENHEIM", 6.55, None, True, "Bourgogne"),
    Cremant("Crémant de Limoux PIERRE DE VOISINS REFLETS DE FRANCE", 6.35, None, True, "Limoux"),
    Cremant("Crémant de Limoux AGUILA", 7.75, None, True, "Limoux"),
    Cremant("Crémant de Bourgogne brut TASTEVINAGE", 7.90, None, True, "Bourgogne"),
    Cremant("Crémant de Loire Brut JAILLANCE", 6.70, 1.0, True, "Loire"),
    Cremant("Crémant de Bourgogne brut Rosé LOUIS BOUILLOT GRANDE RESERVE", 8.95, None, True, "Bourgogne"),
    Cremant("Crémant de Bourgogne brut ARTHUR WEYSBECK", 6.35, None, True, "Bourgogne"),
    Cremant("Crémant de Bourgogne brut MARIE AMBAL", 8.99, 5, True, "Bourgogne"),
    Cremant("Crémant de Loire brut ROSÉ ACKERMAN", 6.95, None, True, "Loire"),
    Cremant("Crémant de Bourgogne brut MARCEL CABELIER ROSÉ 2014", 7.50, None, True, "Bourgogne"),
    Cremant("Crémant d'Alsace brut BLANC DE NOIRS CAVE DE BEBLENHEIM", 6.95, None, True, "Alsace"),
    Cremant("Crémant d'Alsace brut BLANC DE BLANCS ARTHUR METZ", 6.90, None, True, "Alsace"),
    Cremant("Crémant de Bourgogne brut TASTEVINAGE MARIE AMBAL", 8.99, 5, True, "Bourgogne"),
    Cremant("Crémant de Bourgogne brut GRAND RÉSERVE VEUVE AMBAL", 8.95, 5, True, "Bourgogne"),
    Cremant("Crémant de Bourgogne brut CUVÉE DE RÉSERVE DOPFF", 8.35, None, True, "Bourgogne"),
    Cremant("Crémant de Loire brut MONCONTOUR PREMIUM", 7.50, None, True, "Loire"),
    Cremant("Crémant de Limoux brut PRESTIGE PIERRE DE VOISINS", 6.35, None, True, "Limoux"),
    Cremant("Crémant de Bourgogne brut MARIE AMBAL", 8.99, 5, True, "Bourgogne"),
    Cremant("Crémant de Die doux TRADITION JAILLANCE", 3.95, None, True, "Die"),
    Cremant("Crémant de Bourgogne brut CUVÉE ÉQUINOXE", 11.95, None, True, "Bourgogne"),
    Cremant("Crémant de Bourgogne brut ICE VEUVE AMBAL", 22.16, 5, True, "Bourgogne"),
    Cremant("Crémant de Limoux brut BIO SIEUR D'ARQUES", 18.25, None, True, "Limoux"),
    Cremant("Crémant de Bourgogne brut PRESTIGE ARTHUR METZ", 19.79, None, True, "Bourgogne"),
    Cremant("Crémant de Loire brut CUVEÉ RENAISSANCE GRATIEN & MEYER", 19.32, None, True, "Loire"),
    Cremant("Crémant de Die brut MONGE GRANON LOT DE 6", 64.00, None, True, "Die"),
    Cremant("Crémant de Bourgogne brut PINOT NOIR DOPFF", 9.39, None, True, "Bourgogne"),
    Cremant("Crémant d'Alsace brut RÉSERVE ARTHUR METZ", 11.45, None, True, "Alsace"),
    Cremant("Crémant d'Alsace brut PINOT BLANC CUVEÉ 1904 ARTHUR METZ", 6.90, None, True, "Alsace"),
    Cremant("Crémant de Die doux BIO", 15.93, None, True, "Die"),
    Cremant("Crémant de Bourgogne brut EXTRA BRUT VEUVE AMBAL", 9.90, 5, True, "Bourgogne"),
    Cremant("Crémant de Bourgogne brut CUVÉE SPÉCIALE", 8.35, None, True, "Bourgogne"),
    Cremant("Crémant de Bourgogne brut BLANC DE NOIRS CHARLES RANVILLE", 8.30, None, True, "Bourgogne"),
    Cremant("Crémant de Loire brut GRATIEN & MEYER", 19.79, None, True, "Loire"),
    Cremant("Crémant d'Alsace brut BLANC DE BLANCS JEAN GEILER", 7.65, None, True, "Alsace"),
    Cremant("Crémant de Bourgogne brut ROSÉ CUVÉE RÉSERVÉE ARTHUR METZ", 11.45, None, True, "Bourgogne"),
    Cremant("Crémant de Loire brut GRATIEN & MEYER RENAISSANCE", 19.32, None, True, "Loire"),
    Cremant("Crémant de Limoux brut AGUILA PRESTIGE", 18.25, None, True, "Limoux"),
    Cremant("Crémant de Bourgogne brut BLANC DE NOIRS VEUVE AMBAL", 7.10, 5, True, "Bourgogne"),
    Cremant("Crémant de Bourgogne brut GRAND RÉSERVE VEUVE AMBAL ROSÉ", 8.95, 5, True, "Bourgogne"),
    Cremant("Crémant de Loire brut GRATIEN & MEYER CUVÉE RENAISSANCE", 19.79, None, True, "Loire"),
    Cremant("Crémant de Bourgogne brut CHARLES DE COURANCE CUVÉE SPÉCIALE", 11.45, None, True, "Bourgogne"),
    Cremant("Crémant de Loire brut GRATIEN & MEYER RÉSERVE", 19.32, None, True, "Loire"),
    Cremant("Crémant de Loire brut MONCONTOUR BLANC PREMIUM", 7.50, None, True, "Loire"),
    Cremant("Crémant d'Alsace brut BLANC DE NOIRS ARTHUR METZ", 6.55, None, True, "Alsace"),
    Cremant("Crémant d'Alsace brut BLANC DE BLANCS WOLFBERGER", 8.65, None, True, "Alsace"),
    Cremant("Crémant de Die doux TRADITION JAILLANCE 37.5cL", 3.95, None, True, "Die"),
    Cremant("Crémant de Limoux brut AGUILA ROSÉ", 7.75, None, True, "Limoux"),
    Cremant("Crémant d'Alsace brut CUVÉE PRESTIGE DOPFF", 8.35, None, True, "Alsace"),
    Cremant("Crémant de Die brut MONGE GRANON", 15.93, None, True, "Die"),
    Cremant("Crémant de Bourgogne brut EXTRA BRUT VEUVE AMBAL", 9.90, 5, True, "Bourgogne"),
    Cremant("Crémant de Bourgogne brut GRAND PRESTIGE CHARLES RANVILLE", 9.80, None, True, "Bourgogne"),
    Cremant("Crémant d'Alsace brut BLANC DE BLANCS JEAN GEILER", 7.65, None, True, "Alsace"),
    Cremant("Crémant d'Alsace brut BLANC DE NOIRS CAVE DE BEBLENHEIM", 6.95, None, True, "Alsace"),
    Cremant("Crémant de Bourgogne brut MARCEL CABELIER", 7.50, None, True, "Bourgogne"),
    Cremant("Crémant d'Alsace brut BLANC DE BLANCS WOLFBERGER RIESLING", 8.50, None, True, "Alsace"),
    Cremant("Crémant de Die doux BIO CUVEÉ ÉQUINOXE", 64.00, None, True, "Die"),
    Cremant("Crémant de Limoux brut BIO SIEUR D'ARQUES", 18.25, None, True, "Limoux"),
    Cremant("Crémant de Bourgogne brut EXTRA ICE VEUVE AMBAL", 22.16, 5, True, "Bourgogne"),
    Cremant("Crémant de Bourgogne brut TASTEVINAGE CUVÉE RÉSERVÉE", 7.90, None, True, "Bourgogne"),
    Cremant("Crémant de Limoux brut PIERRE DE VOISINS", 6.35, None, True, "Limoux"),
    Cremant("Crémant de Loire brut MONCONTOUR CUVÉE PRESTIGE", 7.50, None, True, "Loire"),
    Cremant("Crémant de Bourgogne brut VEUVE AMBAL ROSÉ", 8.50, 5, True, "Bourgogne"),
    Cremant("Crémant de Loire brut CUVÉE ÉQUINOXE BIO", 19.79, None, True, "Loire"),
        Cremant("Crémant d'Alsace brut CUVÉE PRESTIGE DOPFF AU MOULIN", 8.35, None, True, "Alsace"),
    Cremant("Crémant de Die doux TRADITION JAILLANCE", 3.95, None, True, "Die"),
    Cremant("Crémant de Limoux brut AGUILA", 7.75, None, True, "Limoux"),
    Cremant("Crémant de Bourgogne brut CHARLES RANVILLE", 8.30, None, True, "Bourgogne"),
    Cremant("Crémant de Loire brut GRATIEN & MEYER", 19.79, None, True, "Loire"),
    Cremant("Crémant d'Alsace brut BLANC DE BLANCS JEAN GEILER", 7.65, None, True, "Alsace"),
    Cremant("Crémant de Loire brut MONCONTOUR", 7.50, None, True, "Loire"),
    Cremant("Crémant de Limoux brut BIO SIEUR D'ARQUES", 18.25, None, True, "Limoux"),
    Cremant("Crémant de Bourgogne brut VEUVE AMBAL", 8.95, 5, True, "Bourgogne"),
    Cremant("Crémant d'Alsace brut DOPFF AU MOULIN", 8.35, None, True, "Alsace"),
    Cremant("Crémant de Bourgogne brut ROSÉ LOUIS BOUILLOT", 8.95, None, True, "Bourgogne"),
    Cremant("Crémant de Loire brut ACKERMAN", 6.90, None, True, "Loire"),
    Cremant("Crémant d'Alsace brut BLANC DE NOIRS WOLFBERGER", 8.50, None, True, "Alsace"),
    Cremant("Crémant de Die brut BIO", 15.93, None, True, "Die"),
    Cremant("Crémant de Loire brut GRATIEN & MEYER RÉSERVE", 19.32, None, True, "Loire"),
    Cremant("Crémant de Die doux ÉQUINOXE JAILLANCE", 64.00, None, True, "Die"),
    Cremant("Crémant de Bourgogne brut ICE VEUVE AMBAL", 22.16, 5, True, "Bourgogne"),
    Cremant("Crémant de Limoux brut ROSÉ PIERRE DE VOISINS", 6.35, None, True, "Limoux"),
    Cremant("Crémant de Loire brut ROSÉ MONCONTOUR", 7.50, None, True, "Loire"),
    Cremant("Crémant de Limoux brut GRANON", 11.95, None, True, "Limoux"),
    Cremant("Crémant d'Alsace brut BIO WOLFBERGER", 9.25, None, True, "Alsace"),
    Cremant("Crémant de Loire brut CUVEÉ GRATIEN & MEYER", 19.32, None, True, "Loire"),
    Cremant("Crémant de Bourgogne brut TASTEVINAGE ROSÉ VEUVE AMBAL", 7.90, 5, True, "Bourgogne"),
    Cremant("Crémant d'Alsace brut ROSÉ ARTHUR METZ", 8.35, None, True, "Alsace"),
    Cremant("Crémant de Loire brut ROSÉ BIO CARREFOUR", 7.75, None, True, "Loire"),
    Cremant("Crémant de Die brut TRADITION", 6.99, None, True, "Die"),
    Cremant("Crémant de Bourgogne brut PRESTIGE ARTHUR METZ", 19.79, None, True, "Bourgogne"),
    Cremant("Crémant de Bourgogne brut BLANC DE BLANCS VEUVE AMBAL", 9.90, 5, True, "Bourgogne"),
    Cremant("Crémant d'Alsace brut ICE ROSÉ WOLFBERGER", 6.80, None, True, "Alsace"),
    Cremant("Crémant de Die brut ROSÉ JAILLANCE", 6.70, None, True, "Die"),
    Cremant("Crémant d'Alsace brut JEAN GEILER", 7.65, None, True, "Alsace"),
    Cremant("Crémant de Bourgogne brut DOMAINE GRACIEUX CHEVALIER", 8.69, None, True, "Bourgogne"),
    Cremant("Crémant de Die brut TRADITION BIO JAILLANCE", 64.00, None, True, "Die"),
    Cremant("Crémant de Limoux brut AGUILA PRESTIGE", 18.25, None, True, "Limoux"),
    Cremant("Crémant de Bourgogne brut MARCEL CABELIER ROSÉ", 7.50, None, True, "Bourgogne"),
    Cremant("Crémant d'Alsace brut BIO E.DURENMEYER", 8.65, None, True, "Alsace"),
    Cremant("Crémant de Bourgogne brut ROSÉ BIO VEUVE AMBAL", 8.99, 5, True, "Bourgogne"),
    Cremant("Crémant de Loire brut CUVEÉ PRESTIGE MONCONTOUR", 7.50, None, True, "Loire"),
    Cremant("Crémant de Bourgogne brut ROSÉ PRESTIGE", 19.79, None, True, "Bourgogne"),
]

new_wines = [
    Prosecco("Vin Blanc D.O.C. Prosecco SIGNORI DEI DOGI TREVISO EXTRA DRY", 5.95, 4.43, True),
    Prosecco("Vin Blanc D.O.C. Prosecco Treviso Brut MIONETTO PRESTIGE", 7.75, 4.53, True),
    Prosecco("Vin Blanc D.O.C. Prosecco SIGNORE GIUSEPPE EXTRA DRY", 6.69, 4.0, True),
    Prosecco("Vin Blanc D.O.C. Prosecco Extra Dry PERLINO", 6.85, 4.48, True),
    Prosecco("Vin Blanc D.O.C. Prosecco VILAVERONI", 7.99, None, True),
    Prosecco("Vin Rosé D.O.C. PROSECCO SIGNORIA DEI DOGI", 5.95, 4.37, True),
    Prosecco("Vin Blanc Pétillant Extra Dry Prosecco RICCADONIA", 6.85, 4.45, True),
    Prosecco("Vin Rosé D.O.C. Prosecco Rosé VILAVERONI", 7.99, 4.67, True),
    Prosecco("Vin Blanc D.O.C. Prosecco Extra Dry SIGNORIA DEI DOGI", 6.95, 5.0, True),
    Prosecco("Vin Blanc D.O.C. Prosecco Treviso CANTINE MASCHIO EXTRA DRY", 7.45, 4.33, True),
    Prosecco("Vin Blanc A.O.P. Prosecco SIGNORI DEI DOGI", 7.99, 5.0, True),
    Prosecco("Vin Blanc Pétillant Mionetto Bio PROSECCO", 9.05, 4.5, True),
    Prosecco("Vin Blanc A.O.P. Italie Prosecco Extra Dry SIGNORIA DEI DOGI", 4.15, None, True),
    Prosecco("Vin Blanc A.O.P. Italie Prosecco Extra Dry RICCADONIA", 4.69, None, True),
    Prosecco("Vin Blanc Pétillant Extra Dry Prosecco RICCADONNA", 8.59, 5.0, True),
    Prosecco("Vin pétillant Prosecco LA CERIOLA", 8.85, 5.0, True),
    Prosecco("Vin Rosé Mousseux Prosecco RICCADONNA", 9.55, None, True),
    Prosecco("Prosecco La Gioiosa Etamorosa Brut Gold Label 75 Cl", 19.82, None, True),
    Prosecco("Vin Blanc D.O.C. Prosecco Biologico VILAVERONI", 8.95, None, True),
    Prosecco("Vin pétillant prosecco BELLUSSI", 7.85, None, True),
    Prosecco("Vin pétillant Prosecco LA CERIOLA", 16.05, None, True),
    Prosecco("Vin Blanc d'Italie Prosecco D.O.C. BERNARD MAGREZ", 8.40, None, True),
    Prosecco("Vin pétillant Prosecco brut ANDREA BERRO", 9.59, 4.0, True),
    Prosecco("Vin Blanc A.O.P. Pétillant Prosecco D.O.C. Extra Dry MASCHIO", 9.99, None, True),
    Prosecco("Vin pétillant Prosecco Extra Dry VILLA JOLANDA", 7.80, None, True),
    Prosecco("Vin Blanc Pétillant D.O.C. Prosecco Extra Dry DE NOBILI", 10.75, None, True),
    Prosecco("Prosecco Costa Pétillant Années 80", 58.65, None, True),
    # NonAlcoholicSparkling("Vin Blanc Sans Alcool Pétillant Blanc de Blanc LE PETIT BERET", 7.55, 3.0, True),
    # BlanquetteDeLimoux("Blanquette de Limoux brut AIMERY", 5.80, 4.0, True),
    Cremant("Crémant de Bourgogne brut L'AURORE", 7.00, 4.0, True, "Bourgogne"),
    Cremant("Crémant d'Alsace brut ARTHUR METZ", 9.80, 5.0, True, "Alsace"),
    Cremant("Crémant de Die brut JAILLANCE", 6.99, 4.5, True,"Drôme"),
]


sparkling_wine.extend(new_wines)

mousseux_wines = [
    Mousseux("Vin Blanc Mousseux Brut SIRE DE BEAUPRE", 1.75, 5.0, True, "France"),
    Mousseux("Vin Blanc Mousseux Brut J.KIEFFER", 3.00, 4.11, True, "France"),
    Mousseux("Vin Blanc Mousseux demi-Sec J.KIEFFER", 3.00, 4.39, True, "France"),
    Mousseux("Vin Mousseux Blanc de Blanc Brut de qualité CHARLES VOLNER", 4.35, 5.0, True, "France"),
    Mousseux("Vin Blanc Mousseux demi-Sec SIRE DE BEAUPRE", 1.75, 5.0, True, "France"),
    Mousseux("Vin Mousseux Blanc de Blanc Brut OPERA", 3.65, 5.0, True, "France"),
    Mousseux("Vin Rosé Mousseux demi-Sec Rosé J.KIEFFER", 3.00, 4.17, True, "France"),
    Mousseux("Vin Blanc A.O.P. Pétillant Brut Vouvray DESIRE SOUDRILLE", 6.89, 5.0, True, "France"),
    Mousseux("Vin Mousseux Muscat Blanc MUSCADOR", 2.89, 3.67, True, "France"),
]

sparkling_wine.extend(mousseux_wines)